# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  body_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  versioning: true
  view:
    view_response_listener: 'force'
    formats:
      json: true
