version: "3.1"
services:

    mysql:
      image: mysql:8.0
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_DATABASE=${DATABASE_NAME}
        - MYSQL_USER=${DATABASE_USER}
        - MYSQL_PASSWORD=${DATABASE_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      ports:
        - "12004:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "12002:80"

    php:
      build: docker/php-fpm
      working_dir: /application
      environment:
        - APP_ENV=${APP_ENV}
        - APP_SECRET=${APP_SECRET}
        - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:3306/${DATABASE_NAME}?serverVersion=5.7
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

